#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [ ! -d "venv" ]; then
    python3 -m venv venv
fi

venv/bin/pip install --requirement requirements.txt
venv/bin/pip install pre-commit
venv/bin/pre-commit install
